name: test & lint 
run-name: test & lint run on ${{ github.ref_name }}
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17'
      - uses: golangci/golangci-lint-action@v3
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17'
      - name: Run tests
        run: make pkg_test
  E2E-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '>=1.17'
      - name: Run e2e tests
        run: make e2e_test
